// Tableau des breakpoints
export const BREAKPOINTS = [
	{
		size: 'xsmall',
		min: 0,
		max: 359,
		colMax: 4,
		isMobile: true,
		isTablet: false,
		isLaptop: false,
		isDesktop: false,
		screen: 'mobile',
	},
	{
		size: 'xsmall',
		min: 360,
		max: 399,
		colMax: 4,
		isMobile: true,
		isTablet: false,
		isLaptop: false,
		isDesktop: false,
		screen: 'mobile',
	},
	{
		size: 'xsmall',
		min: 400,
		max: 479,
		colMax: 4,
		isMobile: true,
		isTablet: false,
		isLaptop: false,
		isDesktop: false,
		screen: 'mobile',
	},
	{
		size: 'xsmall',
		min: 480,
		max: 599,
		colMax: 4,
		isMobile: true,
		isTablet: true,
		isLaptop: false,
		isDesktop: false,
		screen: 'mobile',
	},
	{
		size: 'small',
		min: 600,
		max: 719,
		colMax: 8,
		isMobile: false,
		isTablet: true,
		isLaptop: false,
		isDesktop: false,
		screen: 'Tablet',
	},
	{
		size: 'small',
		min: 720,
		max: 839,
		colMax: 8,
		isMobile: false,
		isTablet: true,
		isLaptop: false,
		isDesktop: false,
		screen: 'Tablet',
	},
	{
		size: 'small',
		min: 840,
		max: 1023,
		colMax: 12,
		isMobile: false,
		isTablet: true,
		isLaptop: false,
		isDesktop: false,
		screen: 'Tablet',
	},
	{
		size: 'medium',
		min: 1024,
		max: 1279,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: true,
		isDesktop: false,
		screen: 'Laptop',
	},
	{
		size: 'large',
		min: 1280,
		max: 1439,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: false,
		isDesktop: true,
		screen: 'Desktop',
	},
	{
		size: 'large',
		min: 1440,
		max: 1599,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: false,
		isDesktop: true,
		screen: 'Desktop',
	},
	{
		size: 'large',
		min: 1600,
		max: 1919,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: false,
		isDesktop: true,
		screen: 'Desktop',
	},
	{
		size: 'xlarge',
		min: 1920,
		max: 1980,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: false,
		isDesktop: true,
		screen: 'Large Desktop',
	},
	{
		size: 'xlarge',
		min: 1981,
		max: 3860,
		colMax: 12,
		isMobile: false,
		isTablet: false,
		isLaptop: false,
		isDesktop: true,
		screen: 'Very Large Desktop',
	},
];
// Recherche du preakpoint correspondant
export function getBreakPoint(currentsize) {
	if (
		currentsize === undefined ||
		currentsize < 0 ||
		currentsize > BREAKPOINTS[BREAKPOINTS.length - 1].max
	) {
		throw 'Taille du device invalide - ' + currentsize;
	}

	var bp = BREAKPOINTS.filter((bp) => currentsize >= bp.min && currentsize <= bp.max);
	if (bp) return bp[0];
	else return {};
}
