const Story = {
  titre: "SOS Planète, l'histoire",
  chapitres: [
    {
      id: 0,
      titre: "Le rêve",
      resume: "Jo j'ai fait un rêve étrange ! Moi aussi, Isabelle, dit Jo",
      content: "/audio/sos/chap-01/recit.mp3",
      illustrations: [
        "/audio/sos/chap-01/images/02-Isabelle.png",
        "/audio/sos/chap-01/images/03-Mon-copain-Jo.png",
        "/audio/sos/chap-01/images/04-Ma-classe.png",
        "/audio/sos/chap-01/images/05-Les-chats.png",
        "/audio/sos/chap-01/images/06-Toujours-ensemble.png",
        "/audio/sos/chap-01/images/07-Bavardage.png",
        "/audio/sos/chap-01/images/08-Attend-Jo.png",
        "/audio/sos/chap-01/images/09-Jo-bandage.png",
        "/audio/sos/chap-01/images/10-Impatiente-raconter-reve.png",
        "/audio/sos/chap-01/images/11-Isabelle-attend-Jo.png",
        "/audio/sos/chap-01/images/12-Reve-isabelle.png",
        "/audio/sos/chap-01/images/13-Reve-identique.png",
        "/audio/sos/chap-01/images/14-La-parlotte.png",
        "/audio/sos/chap-01/images/15-Enfants-faisant-meme-reve.png",
        "/audio/sos/chap-01/images/16-Resoudre-mystere.png",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 1,
      titre: "L'enquête",
      resume: "Isabelle, il faut que nous menons l'enquête dit Jo",
      content: "/audio/sos/chap-02/recit.mp3",
      illustrations: [
        "/audio/sos/chap-02/images/01-Debut_enquete.png",
        "/audio/sos/chap-02/images/02-Reve_Marilou.png",
        "/audio/sos/chap-02/images/03-Classe_ecoute_Marilou.png",
        "/audio/sos/chap-02/images/04-Classe_yeux_fermes.png",
        "/audio/sos/chap-02/images/05-Maxime_ractonte.png",
        "/audio/sos/chap-02/images/06-Dinosaure_sort_oeuf.png",
        "/audio/sos/chap-02/images/07-Dinosaure_mange_feuilles.png",
        "/audio/sos/chap-02/images/08-Les_3_Triceratops.png",
        "/audio/sos/chap-02/images/09-Maitresse-boouche-bee.png",
        "/audio/sos/chap-02/images/10-Triceratops_mangent.png",
        "/audio/sos/chap-02/images/11-Triceratops_Diplodocus.png",
        "/audio/sos/chap-02/images/12-Tyranosaure_et_volcan.png",
        "/audio/sos/chap-02/images/13-Triceratops_effrayes.png",
        "/audio/sos/chap-02/images/14-Diplodocus_mange.png",
        "/audio/sos/chap-02/images/15-Diplodocus_donne_manger.png",
        "/audio/sos/chap-02/images/16-Dinosaures_partent.png",
        "/audio/sos/chap-02/images/17-Isa_et_jo_reve_encore.png",
        "/audio/sos/chap-02/images/18-Quelle_morale.png",
        "/audio/sos/chap-02/images/19-Classe_terminee.png",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 2,
      titre: "Extinction",
      resume: "Tu l'as vu aussi, Jo, l'extinction des dinosaures ?",
      content: "/audio/sos/chap-03/recit.mp3",
      illustrations: [
        "/audio/sos/chap-03/images/01-Isa_discute_Jo.png",
        "/audio/sos/chap-03/images/02-Isa_aide_cantine_petit.png",
        "/audio/sos/chap-03/images/03-Isa_fiere_grande.png",
        "/audio/sos/chap-03/images/04-Isa_attend.png",
        "/audio/sos/chap-03/images/05-Explication_trie_dechet.png",
        "/audio/sos/chap-03/images/06-Recycler.png",
        "/audio/sos/chap-03/images/07-Atelier_trie.png",
        "/audio/sos/chap-03/images/08-Enfants_ennuient.png",
        "/audio/sos/chap-03/images/01-Isa_discute_Jo.png",
        "/audio/sos/chap-03/images/09-Vallee_verdoyante.png",
        "/audio/sos/chap-03/images/10-Dinosaures_courent_car_peur.png",
        "/audio/sos/chap-03/images/11-Vallee_jauni.png",
        "/audio/sos/chap-03/images/12-Dinosaures_traversent_vallee.png",
        "/audio/sos/chap-03/images/13-Valle_desertique.png",
        "/audio/sos/chap-03/images/14-Dynosaures_perplexes.png",
        "/audio/sos/chap-03/images/15-Planete_desertique.png",
        "/audio/sos/chap-03/images/16-Lanceurs_alerte.png",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 3,
      titre: "Lanceur d'alerte",
      resume: "Qu'est-ce que c'est un lanceur d'alerte ?",
      content: "/audio/sos/chap-04/recit.mp3",
      illustrations: [
        "/audio/sos/chap-04/images/01-Lanceurs_alerte.png",
        "/audio/sos/chap-04/images/02-Isabelle_pas_concentre.png",
        "/audio/sos/chap-04/images/03-Isabelle_lit_courament.png",
        "/audio/sos/chap-04/images/04-Isabelle_declic_lecture.png",
        "/audio/sos/chap-04/images/05-Isabelle_illumination.png",
        "/audio/sos/chap-04/images/06-Isabelle_ennuie.png",
        "/audio/sos/chap-04/images/07-Isabelle_cherche_livres.png",
        "/audio/sos/chap-04/images/08-Isabelle_lit_sous_le_bureau.png",
        "/audio/sos/chap-04/images/09-Isabelle_recupere_dictionnaire.png",
        "/audio/sos/chap-04/images/10-Isabelle_definition_lanceur_alerte.png",
        "/audio/sos/chap-04/images/11-Extinction_dinosaure.png",
        "/audio/sos/chap-04/images/12-Extinction_dinosaures.jpg",
        "/audio/sos/chap-04/images/13-Classe_terminee-1.png",
        "/audio/sos/chap-04/images/14-Sortie_ecole.jpg",
        "/audio/sos/chap-04/images/15-Discussion_repas_soir.jpg",
        "/audio/sos/chap-04/images/16-Comment_alerter.jpg",
        "/audio/sos/chap-04/images/17-Trie_dechets.png",
        "/audio/sos/chap-04/images/18-Isabelle_reflechi_dans_lit.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 4,
      titre: "L'idée",
      resume: "J'ai une idée, dit Jo, et si ...",
      content: "/audio/sos/chap-05/recit.mp3",
      illustrations: [
        "/audio/sos/chap-05/images/01-Isabelle_en_retard.jpg",
        "/audio/sos/chap-05/images/02-Jo_a_une_idee.jpg",
        "/audio/sos/chap-05/images/03-les_menottes.jpg",
        "/audio/sos/chap-05/images/04-Jo_raconte_idee.jpg",
        "/audio/sos/chap-05/images/05-Jo_murmure_oreille_isabelle.jpg",
        "/audio/sos/chap-05/images/06-Isabelle_reflechi.jpg",
        "/audio/sos/chap-05/images/07-Jo_donne_papier.jpg",
        "/audio/sos/chap-05/images/08-Isabelle_mange.jpg",
        "/audio/sos/chap-05/images/09-Isabelle_ecrit_lettre.jpg",
        "/audio/sos/chap-05/images/10-Isabelle_a_oublie_une_chose.jpg",
        "/audio/sos/chap-05/images/11-Isabelle_se_cache.jpg",
        "/audio/sos/chap-05/images/12-Jo_et_Isabelle_se_cachent.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 5,
      titre: "La folle nuit",
      resume: "Allez on se retrouve ce soir devant l'école ...",
      content: "/audio/sos/chap-06/recit.mp3",
      illustrations: [
        "/audio/sos/chap-06/images/01-Jo_Isabelle_dans_ecole.jpg",
        "/audio/sos/chap-06/images/02-Jo_Isabelle_boite.jpg",
        "/audio/sos/chap-06/images/03-Jo_Isabelle_avec lampe.jpg",
        "/audio/sos/chap-06/images/04-Jo_Isabelle_dans_couloir.jpg",
        "/audio/sos/chap-06/images/05-Jo_appelle_journaliste.jpg",
        "/audio/sos/chap-06/images/06-Jo_parle_journaliste.jpg",
        "/audio/sos/chap-06/images/07-Jo_Isabelle_mange_gateaux.jpg",
        "/audio/sos/chap-06/images/08-Jo_Isabelle_prepare_lit.jpg",
        "/audio/sos/chap-06/images/09-Jo_Isabelle_menottes.jpg",
        "/audio/sos/chap-06/images/10-Jo_Isabelle_jouent_cartes.jpg",
        "/audio/sos/chap-06/images/11-Isabelle_pense_parents.jpg",
        "/audio/sos/chap-06/images/12-Isabelle_raconte_histoire.jpg",
        "/audio/sos/chap-06/images/13-Jo_Isabelle_decouvert.jpg",
        "/audio/sos/chap-06/images/14-Isabelle_retrouve_parents.jpg",
        "/audio/sos/chap-06/images/15-Isabelle_journaliste.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: true,
    },
    {
      id: 6,
      titre: "Le Journaliste",
      resume: "Monsieur le journaliste, je vais vous dire pourquoi nous avons fait cela ...",
      content: "/audio/sos/chap-07/recit.mp3",
      illustrations: [
        "/audio/sos/chap-07/images/01-Isabelle_se_fait_disputer.jpg",
        "/audio/sos/chap-07/images/02-Petit_dejeuner.jpg",
        "/audio/sos/chap-07/images/03-Isabelle_et_jo_bureau_directrice.jpg",
        "/audio/sos/chap-07/images/04-Jo_parle_jounaliste.jpg",
        "/audio/sos/chap-07/images/05-Jo_Isabelle_sorte_bureau.jpg",
        "/audio/sos/chap-07/images/06-Journaliste_donne_carte_visite.jpg",
        "/audio/sos/chap-07/images/07-Jo-Isabelle_dans_classe.jpg",
        "/audio/sos/chap-07/images/08-Jo-Isabelle_sortent_ecole.jpg",
        "/audio/sos/chap-07/images/09-Isabelle_lit_journal.jpg",
        "/audio/sos/chap-07/images/09-Isabelle_lit_journal-2.jpg",
        "/audio/sos/chap-07/images/10-Cataclysmes.jpg",
        "/audio/sos/chap-07/images/10-Carte cataclysmes.jpg",
        "/audio/sos/chap-07/images/10-Pere_ne_veut_pas_journal_ecole.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
    {
      id: 7,
      titre: "Le Jeu (partie 1)",
      resume: "Un jeu, mais c'est une excellente idée",
      content: "/audio/sos/chap-08/recit.mp3",
      illustrations: [
        "/audio/sos/chap-08/images/01-Enfants_lisent_journal.jpg",
        "/audio/sos/chap-08/images/02-Jo_Isabelle_heureux.jpg",
        "/audio/sos/chap-08/images/03-Questions_en_classe.jpg",
        "/audio/sos/chap-08/images/04-Enfants_expliquent_rechauffement.jpg",
        "/audio/sos/chap-08/images/05-Maitresse_laisse_enfants_parler.jpg",
        "/audio/sos/chap-08/images/06-Dessin_maitresse.jpg",
        "/audio/sos/chap-08/images/07-Dessin_final_maitresse.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
    {
      id: 8,
      titre: "Le Jeu (partie 2)",
      resume: "Mais comment fonctionne le jeu ?",
      content: "/audio/sos/chap-09/recit.mp3",
      illustrations: [
        "/audio/sos/chap-09/images/01-Jo_murmure_a_Isabelle.jpg",
        "/audio/sos/chap-09/images/02-Jo_Isabelle_fouille_placard.jpg",
        "/audio/sos/chap-09/images/03-Jo_Isabelle_trie_placard.jpg",
        "/audio/sos/chap-09/images/04-Isabelle_lit_Ratus.jpg",
        "/audio/sos/chap-09/images/05-Isabelle_Jo_assis_avec_livres.jpg",
        "/audio/sos/chap-09/images/06-Jo_Isabelle_cantine.jpg",
        "/audio/sos/chap-09/images/07-Isabelle_explique_jeu.jpg",
        "/audio/sos/chap-09/images/08-Recompense_jeu.jpg",
        "/audio/sos/chap-09/images/09-Enfants_enthousiates.jpg",
        "/audio/sos/chap-09/images/10-Enfants_enthousiastes.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
    {
      id: 9,
      titre: "La récompense",
      resume: "Je sais comment faire Jo, dit Isabelle",
      content: "/audio/sos/chap-10/recit.mp3",
      illustrations: [
        "/audio/sos/chap-10/images/01-Isabelle_court_vers_Jo.jpg",
        "/audio/sos/chap-10/images/02-Isabelle_montre_caret_visite.jpg",
        "/audio/sos/chap-10/images/03-Isabelle_parle_a_Jo.jpg",
        "/audio/sos/chap-10/images/03bis-Jo_parle_Isabelle.jpg",
        "/audio/sos/chap-10/images/04-Isabelle_et_jo_attende_recreation.jpg",
        "/audio/sos/chap-10/images/05-Isabelle-jo-range_placard.jpg",
        "/audio/sos/chap-10/images/06-Isabelle_compose_numero.jpg",
        "/audio/sos/chap-10/images/07-Isabelle_laisse_message_repondeur.jpg",
        "/audio/sos/chap-10/images/08-Directrice_mecontente.jpg",
        "/audio/sos/chap-10/images/09-Isabelle_telephone_journaliste.jpg",
        "/audio/sos/chap-10/images/10-Journaliste_parle_Isabelle.jpg",
        "/audio/sos/chap-10/images/11-Isabelle_reflechi.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
    {
      id: 10,
      titre: "La lettre",
      resume: "Et si on ecrivait une lettre ?",
      content: "/audio/sos/chap-11/recit.mp3",
      illustrations: [
        "/audio/sos/chap-11/images/01-Directrice_explique_jeu.jpg",
        "/audio/sos/chap-11/images/02-Enfants_discutent_actions.jpg",
        "/audio/sos/chap-11/images/03-Liste_actions.jpg",
        "/audio/sos/chap-11/images/04-Isabelle_compte_actions.jpg",
        "/audio/sos/chap-11/images/05-Kermesse_ecole.jpg",
        "/audio/sos/chap-11/images/06-Isabelle_compte_actions.jpg",
        "/audio/sos/chap-11/images/07-Maitresse_prend_photo.jpg",
        "/audio/sos/chap-11/images/08-President_remet_prix.jpg",
        "/audio/sos/chap-11/images/09-Isabelle_applaudi.jpg",
        "/audio/sos/chap-11/images/10-Isabelle_ecrit_lettre.jpg",
        "/audio/sos/chap-11/images/11-Isabelle_reflechit.jpg",
        "/audio/sos/chap-11/images/12-Isabelle_depose_lettre.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
    {
      id: 11,
      titre: "La Kermesse",
      resume: "",
      content: "/audio/sos/chap-12/recit.mp3",
      illustrations: [
        "/audio/sos/chap-12/images/01-Isabelle_note_actions.jpg",
        "/audio/sos/chap-12/images/02-Isabelle_poistionne_aimant.jpg",
        "/audio/sos/chap-12/images/03-Isabelle_et_jo_regarde_autres_classes.jpg",
        "/audio/sos/chap-12/images/04-Tableau_avec_aimants.jpg",
        "/audio/sos/chap-12/images/05-Maitresse_montre_multiplication.jpg",
        "/audio/sos/chap-12/images/06-Maitresse_porte_lettre_president.jpg",
        "/audio/sos/chap-12/images/07-Maitresse_discute_avec_jo_et_isabelle.jpg",
        "/audio/sos/chap-12/images/08-Jo_et_Isabelle_saute_de_joie.jpg",
        "/audio/sos/chap-12/images/09-Enfants_vainqueurs.jpg",
        "/audio/sos/chap-12/images/10-Classe_gagnante.jpg",
        "/audio/sos/chap-12/images/11-Kermesse.jpg",
        "/audio/sos/chap-12/images/12-President_arrive.jpg",
        "/audio/sos/chap-12/images/13-Jo_Isabelle_parle_president.jpg",
        "/audio/sos/chap-12/images/14-President_dans_chateau_gonflable.jpg",
        "/audio/sos/chap-12/images/15-President_devant_estrade.jpg",
        "/audio/sos/chap-12/images/16-President_remet_prix.jpg",
        "/audio/sos/chap-12/images/17-President_parle_0.jpg",
        "/audio/sos/chap-12/images/17-President_parle_1.jpg",
        "/audio/sos/chap-12/images/18-President_part.jpg",
        "/audio/sos/chap-12/images/19-Enfants_jouent_kermesse.jpg",
        "/audio/sos/chap-12/images/20-Isabelle_reve_0.jpg",
        "/audio/sos/chap-12/images/20-Isabelle_reve_1.jpg",
        "/audio/sos/chap-12/images/21-Isabelle_petit_dejeuner.jpg",
        "/audio/sos/chap-12/images/22-Isabelle_accroche_photo_journal.jpg",
        "/audio/sos/chap-12/images/23-Image_de_fin.jpg",
      ],
      illustrationIndex: -1,
      isPlaying: false,
      isReaded: true,
      disponible: false,
    },
  ],
};

export default Story;
