services:
  db:
    image: postgres:15-alpine
    container_name: sos_db_local
    environment:
      - POSTGRES_DB=nnauru
      - POSTGRES_USER=nnauru
      - POSTGRES_PASSWORD=me4nnauru
    ports:
      - "5433:5432"
