-- 1. GameConfig (Colonnes de dates de jeu)
ALTER TABLE "GameConfig" ADD COLUMN IF NOT EXISTS "gameStartDate" TIMESTAMP(3);
ALTER TABLE "GameConfig" ADD COLUMN IF NOT EXISTS "gameEndDate" TIMESTAMP(3);
ALTER TABLE "GameConfig" ADD COLUMN IF NOT EXISTS "gamePeriodsCount" INTEGER NOT NULL DEFAULT 24;

-- 2. SystemConfig (Valeurs de référence)
ALTER TABLE "SystemConfig" ADD COLUMN IF NOT EXISTS "emissionsParHabitantAn" DOUBLE PRECISION NOT NULL DEFAULT 11.0;
ALTER TABLE "SystemConfig" ADD COLUMN IF NOT EXISTS "temperatureMalade" DOUBLE PRECISION NOT NULL DEFAULT 42.0;
ALTER TABLE "SystemConfig" ADD COLUMN IF NOT EXISTS "temperatureSaine" DOUBLE PRECISION NOT NULL DEFAULT 37.0;
ALTER TABLE "SystemConfig" ADD COLUMN IF NOT EXISTS "populationReference" INTEGER NOT NULL DEFAULT 68000000;
